// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projects.Data;

#nullable disable

namespace projects.Migrations
{
    [DbContext(typeof(PetrolStationContext))]
    [Migration("20231116024258_SeedDatav2")]
    partial class SeedDatav2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("projects.Models.Station", b =>
                {
                    b.Property<int>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<double>("Lat")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "lon");

                    b.Property<string>("LocationType")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.Property<double>("Lon")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "lat");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.HasKey("StationId");

                    b.HasIndex("TagId");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            StationId = 30092081,
                            Lat = -1.2990005,
                            LocationType = "node",
                            Lon = 36.759717299999998,
                            TagId = 30092081
                        });
                });

            modelBuilder.Entity("projects.Models.Tag", b =>
                {
                    b.Property<int?>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amenity")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "amenity");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "brand");

                    b.Property<string>("City")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "addr:city");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "operator");

                    b.Property<string>("Street")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "addr:street");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasAnnotation("Relational:JsonPropertyName", "tags");

                    b.HasData(
                        new
                        {
                            TagId = 30092081,
                            Amenity = "fuel",
                            Brand = "Total",
                            City = "Nairobi",
                            Name = "Total",
                            Operator = "Total",
                            Street = "Ngong Road"
                        });
                });

            modelBuilder.Entity("projects.Models.Station", b =>
                {
                    b.HasOne("projects.Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");
                });
#pragma warning restore 612, 618
        }
    }
}
